# golangci-lint v2 configuration for triton_bench
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Default linters (already enabled, but explicit)
    - govet          # Examines Go source code and reports suspicious constructs
    - errcheck       # Checks for unchecked errors
    - staticcheck    # Includes gosimple, now unified in staticcheck
    - ineffassign    # Detects ineffectual assignments
    - unused         # Checks for unused constants, variables, functions and types

    # Additional recommended linters for benchmark/production code
    - gocyclo        # Computes cyclomatic complexity
    - goconst        # Finds repeated strings that could be replaced by constants
    - misspell       # Finds commonly misspelled English words
    - unconvert      # Remove unnecessary type conversions
    - dupl           # Tool for code clone detection
    - revive         # Fast, configurable, extensible linter (golint replacement)
    - nolintlint     # Reports ill-formed nolint directives
    - whitespace     # Detection of leading and trailing whitespace

    # Performance-critical for benchmarks
    - bodyclose      # Checks whether HTTP response bodies are closed
    - prealloc       # Finds slice declarations that could be pre-allocated

  settings:
    gocyclo:
      min-complexity: 15  # Slightly higher for benchmark code with many test paths

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    dupl:
      threshold: 100  # Higher threshold for benchmark code

    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
        - name: unexported-return
        - name: unreachable-code
        - name: redefines-builtin-id

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Struct field alignment is low priority

formatters:
  enable:
    - gofmt          # Checks whether code was gofmt-ed
    - goimports      # gofmt with imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - errcheck
        - goconst

output:
  formats:
    colored-line-number:
      print-issued-lines: true
      print-linter-name: true
  sort-results: true
